name: Build Standalone App

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Publish True Standalone Executable
      # We added WindowsAppSDK deployment overrides to pack absolutely everything into the output folder
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PlatformTarget=x64 -p:WindowsAppSDKPackageRoot=true -p:WindowsPackageType=None -o ./publish-output

    - name: Upload Finished App
      uses: actions/upload-artifact@v4
      with:
        name: FarmManager-True-Standalone
        path: ./publish-output/
